# Use root/example as user/password credentials
version: "3.1"

services:
    db:
        image: mariadb
        restart: always
        ports:
            - 3506:3306
        environment:
            MYSQL_ROOT_PASSWORD: storykit
    frontend:
        image: storykit_test/frontend:latest
        restart: always
        ports:
            - 80:80
    backend:
        image: storykit_test/backend:latest
        restart: always
        ports:
            - 3500:3500
        environment:
            PORT: 3500
        command: node build/main.js